import { Protocol } from "pmtiles";
import { addProtocol, setWorkerUrl, type StyleSpecification } from "maplibre-gl";

let workerUrlConfigured = false;

/** maplibre-gl computes its tile-parsing worker's URL from its own
 * module's `import.meta.url`, resolved relative to itself
 * (`./maplibre-gl-worker.mjs`). Turbopack relocates/rewrites that module
 * into an app chunk, so the computed URL no longer points at the real
 * worker file -- the worker fails to load, and since every vector-tile
 * fetch is dispatched from inside it (via the Actor/Dispatcher message
 * channel), that hangs forever with no console error and no network
 * request: registering a `pmtiles://` protocol handler still works (it's
 * called on the main thread for the initial metadata request), but no
 * actual z/x/y tile request ever reaches it. Confirmed with Playwright's
 * `page.on('worker', ...)`: the worker was created and then immediately
 * closed after a failed relative import of `./maplibre-gl-shared.mjs`,
 * which doesn't exist at the guessed location either.
 *
 * Fix: copy both files verbatim to public/ (scripts/copy-maplibre-worker.mjs,
 * gitignored, regenerated by predev/prebuild) and point `setWorkerUrl` at
 * our copy so maplibre never has to guess. Must run before any
 * `new Map(...)`. */
function ensureWorkerUrlConfigured(): void {
  if (workerUrlConfigured) return;
  setWorkerUrl("/maplibre-gl-worker.mjs");
  workerUrlConfigured = true;
}

let protocolRegistered = false;

/** Registers the `pmtiles://` protocol (via the `pmtiles` package, per
 * CLAUDE.md Section 8's "MapLibre GL + pmtiles.js") and the worker-URL fix
 * above, exactly once. Safe to call from every MapView/CompareView mount. */
export function ensurePmtilesProtocol(): void {
  ensureWorkerUrlConfigured();
  if (protocolRegistered) return;
  const protocol = new Protocol();
  addProtocol("pmtiles", protocol.tile);
  protocolRegistered = true;
}

/** ADR 0002: local dev serves fixture tiles from public/dev-tiles/ (Next
 * static file serving, Range-request capable); a real deployment points
 * this at Vercel Blob/R2 instead — nothing else should need to change. */
export function tilesBaseUrl(): string {
  return process.env.NEXT_PUBLIC_TILES_BASE_URL ?? "/dev-tiles";
}

export function scoresPmtilesUrl(): string {
  return `pmtiles://${tilesBaseUrl()}/scores.pmtiles`;
}

export function anchorsGeojsonUrl(): string {
  return `${tilesBaseUrl()}/anchors.geojson`;
}

export function detailUrl(h3: string): string {
  return `${tilesBaseUrl()}/detail/${h3}.json`;
}

/** Local-dev-only basemap (ADR 0002 addendum): a plain background colour,
 * no external tile source at all. Not tile.openstreetmap.org (forbidden by
 * Section 3), and not the real deployment target either — Section 12 item
 * 9 commits to a self-hosted Protomaps basemap.pmtiles in production,
 * which `tile-builder` has not built yet. An earlier version of this
 * pointed at MapLibre's public demo style (demotiles.maplibre.org); that
 * was dropped because it depends on network reachability this dev
 * environment doesn't reliably have, and it's no closer to the real
 * deployment target than a blank background is. Swap this for the real
 * basemap.pmtiles URL once it exists; nothing else here should need to
 * change. */
export const DEV_BASEMAP_STYLE: StyleSpecification = {
  version: 8,
  sources: {},
  layers: [{ id: "background", type: "background", paint: { "background-color": "#eef2f5" } }],
};
